apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-nginx.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress.webapps.saiapplications.online
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}
    helm.sh/chart: {{ include "ingress-nginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: "35.193.227.137"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
