apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-dns.name" . }}
    helm.sh/chart: {{ include "external-dns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "external-dns.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "external-dns.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: external-dns
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --source=service
          - --source=ingress
          - --domain-filter=webapps.saiapplications.online # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
          - --provider=google
#         - --google-project=zalando-external-dns-test # Use this to specify a project different from the one external-dns is running inside
          - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
          - --registry=txt
          - --txt-owner-id=webapps.saiapplications.online

